import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { ArrowLeft, Copy, Crown, MoreVertical, Plus, Settings, ShieldCheck, Trash2, UserRound } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { toast } from 'sonner'
import { Button } from '../components/ui/Button'
import { Modal } from '../components/ui/Modal'
import { ErrorState, Loading } from '../components/ui/States'
import { useAuth } from '../hooks/useAuth'
import { friendlyError } from '../lib/utils'
import { getGroup, removeMember, updateGroup, updateMemberRole } from '../services/groups.service'
import { createWheel, deleteWheel, updateWheel } from '../services/wheels.service'
import type { Group, GroupMembership, Wheel } from '../types'

export function GroupPage() {
  const { groupId = '' } = useParams(); const { session } = useAuth(); const navigate = useNavigate()
  const [data, setData] = useState<{ group: Group; members: GroupMembership[]; wheels: Wheel[] } | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [newWheel, setNewWheel] = useState(false); const [settings, setSettings] = useState(false); const [editing, setEditing] = useState<Wheel | null>(null)
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await getGroup(groupId)) } catch (e) { setError(friendlyError(e, 'Este grupo no existe o no sos miembro.')) } finally { setLoading(false) } }, [groupId])
  useEffect(() => { void load() }, [load])
  if (loading) return <div className="page"><Loading label="Buscando al grupo..." /></div>
  if (!data || error) return <div className="page"><ErrorState message={error} action={<Link to="/home"><Button>Volver</Button></Link>} /></div>
  const myMembership = data.members.find(m => m.user_id === session?.user.id); const canManage = myMembership?.role === 'OWNER' || myMembership?.role === 'ADMIN'; const isOwner = myMembership?.role === 'OWNER'
  const inviteCode = data.group.invite_code
  async function copyCode() { try { await navigator.clipboard.writeText(inviteCode); toast.success('Código copiado') } catch { toast.error('No pudimos copiarlo. El código es ' + inviteCode) } }
  async function removeWheel(wheel: Wheel) { if (!window.confirm(`¿Eliminar “${wheel.name}”? También se borrará su historial.`)) return; try { await deleteWheel(wheel.id); toast.success('Ruleta eliminada'); await load() } catch (e) { toast.error(friendlyError(e)) } }
  return <div className="page"><Link to="/home" className="mb-5 inline-flex items-center gap-2 text-sm font-bold hover:underline"><ArrowLeft size={18}/> Mis grupos</Link><section className="mb-8 rounded-3xl border-2 border-ink bg-lilac p-5 shadow-brutal sm:p-8"><div className="flex items-start justify-between gap-3"><div><p className="mb-2 text-xs font-black uppercase tracking-widest">Cuartel general</p><h1 className="font-display text-4xl font-black uppercase leading-none sm:text-6xl">{data.group.name}</h1><p className="mt-3 max-w-2xl text-ink/70">{data.group.description || 'Sin descripción. Misterioso.'}</p></div>{isOwner && <Button variant="secondary" size="icon" onClick={() => setSettings(true)} aria-label="Editar grupo"><Settings size={20}/></Button>}</div><div className="mt-6 flex flex-wrap items-center gap-3"><button onClick={copyCode} className="flex items-center gap-3 rounded-xl border-2 border-dashed border-ink bg-white/60 px-4 py-3 font-mono text-lg font-black tracking-[.18em]"><span>{data.group.invite_code}</span><Copy size={18}/></button><span className="text-xs font-bold">Compartilo. Sin excusas.</span></div></section>
    <div className="grid gap-8 lg:grid-cols-[1fr_320px]"><section><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-2xl font-black uppercase">Ruletas</h2>{canManage && <Button onClick={() => setNewWheel(true)}><Plus size={18}/> Nueva</Button>}</div>{data.wheels.length === 0 ? <div className="card text-center"><div className="text-5xl">🎡</div><h3 className="mt-3 text-xl font-black">Todavía no hay ruletas</h3><p className="my-3 text-sm text-ink/60">Creá la primera pregunta imposible.</p>{canManage && <Button onClick={() => setNewWheel(true)}>Crear ruleta</Button>}</div> : <div className="grid gap-4 sm:grid-cols-2">{data.wheels.map((wheel, index) => <div key={wheel.id} className={`card relative overflow-hidden ${index % 2 ? 'bg-mint/35' : 'bg-acid/35'}`}><Link to={`/wheel/${wheel.id}`} className="block pr-8"><span className="text-4xl">{['🎯','🍕','🎮','🎬'][index % 4]}</span><h3 className="mt-3 text-xl font-black">{wheel.name}</h3><p className="mt-1 min-h-10 text-sm text-ink/60">{wheel.description || 'Giramos y listo.'}</p></Link>{canManage && <div className="absolute right-2 top-2 flex"><Button variant="ghost" size="icon" onClick={() => setEditing(wheel)} aria-label="Editar ruleta"><MoreVertical size={18}/></Button><Button variant="ghost" size="icon" onClick={() => removeWheel(wheel)} aria-label="Eliminar ruleta"><Trash2 size={18}/></Button></div>}</div>)}</div>}</section>
      <aside><h2 className="mb-4 font-display text-2xl font-black uppercase">La banda · {data.members.length}</h2><div className="card space-y-4">{data.members.map(member => <MemberRow key={member.id} member={member} isOwner={isOwner} currentUserId={session?.user.id || ''} onChange={load} />)}</div></aside></div>
    <WheelFormModal open={newWheel} onClose={() => setNewWheel(false)} groupId={groupId} onSaved={id => navigate(`/wheel/${id}`)} />
    <WheelFormModal open={Boolean(editing)} onClose={() => setEditing(null)} groupId={groupId} wheel={editing ?? undefined} onSaved={() => { setEditing(null); void load() }} />
    <GroupSettingsModal open={settings} onClose={() => setSettings(false)} group={data.group} onSaved={() => { setSettings(false); void load() }} />
  </div>
}

function MemberRow({ member, isOwner, currentUserId, onChange }: { member: GroupMembership; isOwner: boolean; currentUserId: string; onChange: () => Promise<void> }) { const p = member.profiles; async function change(role: 'ADMIN'|'MEMBER') { try { await updateMemberRole(member.id, role); toast.success('Rol actualizado'); await onChange() } catch (e) { toast.error(friendlyError(e)) } } async function remove() { if (!window.confirm(`¿Sacar a ${p?.display_name} del grupo?`)) return; try { await removeMember(member.id); toast.success('Miembro eliminado'); await onChange() } catch (e) { toast.error(friendlyError(e)) } } return <div className="flex items-center gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full border-2 border-ink bg-paper"><UserRound size={19}/></div><div className="min-w-0 flex-1"><p className="truncate font-bold">{p?.display_name}</p><p className="truncate text-xs text-ink/50">@{p?.username}</p></div>{member.role === 'OWNER' ? <span title="Owner"><Crown size={18}/></span> : member.role === 'ADMIN' ? <span title="Admin"><ShieldCheck size={18}/></span> : null}{isOwner && member.role !== 'OWNER' && member.user_id !== currentUserId && <div className="flex items-center gap-1"><select className="rounded-lg border border-ink bg-white p-1 text-xs font-bold" value={member.role} onChange={e => change(e.target.value as 'ADMIN'|'MEMBER')} aria-label={`Rol de ${p?.display_name}`}><option value="MEMBER">Miembro</option><option value="ADMIN">Admin</option></select><button className="p-1 text-coral" onClick={remove} aria-label={`Eliminar a ${p?.display_name}`}><Trash2 size={17}/></button></div>}</div> }

function WheelFormModal({ open, onClose, groupId, wheel, onSaved }: { open: boolean; onClose: () => void; groupId: string; wheel?: Wheel; onSaved: (id: string) => void }) { const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [busy, setBusy] = useState(false); useEffect(() => { setName(wheel?.name || ''); setDescription(wheel?.description || '') }, [wheel, open]); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { if (wheel) { await updateWheel(wheel.id, name, description); toast.success('Ruleta actualizada'); onSaved(wheel.id) } else { const id = await createWheel(groupId, name, description); toast.success('Ruleta creada'); onSaved(id) } onClose() } catch (err) { toast.error(friendlyError(err)) } finally { setBusy(false) } } return <Modal open={open} onClose={onClose} title={wheel ? 'Editar ruleta' : 'Nueva ruleta'}><form onSubmit={submit} className="space-y-4"><label className="label">Pregunta o nombre<input className="input mt-1" maxLength={80} value={name} onChange={e => setName(e.target.value)} placeholder="¿Qué comemos?" required /></label><label className="label">Descripción <span className="font-normal text-ink/40">(opcional)</span><textarea className="input mt-1 min-h-20 py-3" maxLength={240} value={description} onChange={e => setDescription(e.target.value)} /></label><Button className="w-full" size="lg" disabled={busy}>{busy ? 'Guardando...' : wheel ? 'Guardar cambios' : 'Crear y agregar opciones'}</Button></form></Modal> }
function GroupSettingsModal({ open, onClose, group, onSaved }: { open: boolean; onClose: () => void; group: Group; onSaved: () => void }) { const [name, setName] = useState(group.name); const [description, setDescription] = useState(group.description || ''); const [busy, setBusy] = useState(false); useEffect(() => { setName(group.name); setDescription(group.description || '') }, [group, open]); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { await updateGroup(group.id, name, description); toast.success('Grupo actualizado'); onSaved() } catch (err) { toast.error(friendlyError(err)) } finally { setBusy(false) } } return <Modal open={open} onClose={onClose} title="Editar grupo"><form onSubmit={submit} className="space-y-4"><label className="label">Nombre<input className="input mt-1" value={name} maxLength={60} onChange={e => setName(e.target.value)} required /></label><label className="label">Descripción<textarea className="input mt-1 min-h-20 py-3" value={description} maxLength={240} onChange={e => setDescription(e.target.value)} /></label><Button className="w-full" disabled={busy}>{busy ? 'Guardando...' : 'Guardar'}</Button></form></Modal> }
