import { useEffect, useState, type FormEvent } from 'react'
import { ArrowRight, Plus, Ticket } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { useAuth } from '../hooks/useAuth'
import { createGroup, listMyGroups } from '../services/groups.service'
import type { Group, GroupMembership } from '../types'
import { friendlyError } from '../lib/utils'
import { Button } from '../components/ui/Button'
import { EmptyState, ErrorState, Loading } from '../components/ui/States'
import { Modal } from '../components/ui/Modal'

export function HomePage() {
  const { profile } = useAuth(); const navigate = useNavigate(); const [memberships, setMemberships] = useState<(GroupMembership & { groups: Group })[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [createOpen, setCreateOpen] = useState(false); const [joinOpen, setJoinOpen] = useState(false)
  async function load() { setLoading(true); setError(''); try { setMemberships(await listMyGroups()) } catch (e) { setError(friendlyError(e, 'No pudimos cargar tus grupos.')) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  return <div className="page"><div className="mb-8"><p className="font-bold text-ink/50">Hola, {profile?.display_name || 'vos'} 👋</p><h1 className="font-display text-4xl font-black uppercase leading-none sm:text-6xl">¿Qué decidimos?</h1></div><div className="mb-8 grid grid-cols-2 gap-3"><Button size="lg" onClick={() => setCreateOpen(true)}><Plus /> Crear grupo</Button><Button size="lg" variant="secondary" onClick={() => setJoinOpen(true)}><Ticket /> Tengo código</Button></div>{loading ? <Loading /> : error ? <ErrorState message={error} action={<Button onClick={load}>Reintentar</Button>} /> : memberships.length === 0 ? <EmptyState title="Acá todavía no hay nadie" action={<Button onClick={() => setCreateOpen(true)}>Crear mi primer grupo</Button>}>Armá un grupo, compartí el código y que la ruleta se haga cargo.</EmptyState> : <section><h2 className="mb-4 text-sm font-black uppercase tracking-widest">Tus grupos · {memberships.length}</h2><div className="grid gap-4 md:grid-cols-2">{memberships.map(({ groups: group, role }) => <Link key={group.id} to={`/groups/${group.id}`} className="card group block transition hover:-translate-y-1 hover:shadow-brutal-lg"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full border border-ink bg-lilac/30 px-2 py-1 text-[10px] font-black">{role}</span><h3 className="mt-3 text-2xl font-black">{group.name}</h3><p className="mt-1 line-clamp-2 text-sm text-ink/60">{group.description || 'Sin vueltas. A decidir.'}</p></div><ArrowRight className="transition group-hover:translate-x-1" /></div></Link>)}</div></section>}<CreateGroupModal open={createOpen} onClose={() => setCreateOpen(false)} onCreated={id => navigate(`/groups/${id}`)} /><JoinModal open={joinOpen} onClose={() => setJoinOpen(false)} /></div>
}

function CreateGroupModal({ open, onClose, onCreated }: { open: boolean; onClose: () => void; onCreated: (id: string) => void }) { const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [busy, setBusy] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); try { const id = await createGroup(name, description); toast.success('Grupo creado. Que empiece el caos.'); onClose(); onCreated(id) } catch (err) { toast.error(friendlyError(err)) } finally { setBusy(false) } } return <Modal open={open} onClose={onClose} title="Nuevo grupo"><form onSubmit={submit} className="space-y-4"><label className="label">Nombre<input className="input mt-1" maxLength={60} value={name} onChange={e => setName(e.target.value)} placeholder="Los Pibes" required /></label><label className="label">Descripción <span className="font-normal text-ink/40">(opcional)</span><textarea className="input mt-1 min-h-24 py-3" maxLength={240} value={description} onChange={e => setDescription(e.target.value)} placeholder="El comité de las malas decisiones" /></label><Button className="w-full" size="lg" disabled={busy}>{busy ? 'Creando...' : 'Crear grupo'}</Button></form></Modal> }
function JoinModal({ open, onClose }: { open: boolean; onClose: () => void }) { const navigate = useNavigate(); const [code, setCode] = useState(''); function submit(e: FormEvent) { e.preventDefault(); onClose(); navigate(`/join/${code.trim().toUpperCase()}`) } return <Modal open={open} onClose={onClose} title="Usar un código"><form onSubmit={submit} className="space-y-4"><label className="label">Código de invitación<input className="input mt-1 text-center font-mono text-2xl font-black uppercase tracking-[.25em]" minLength={6} maxLength={8} value={code} onChange={e => setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ''))} placeholder="K7P4XZ" required /></label><Button className="w-full" size="lg">Buscar grupo</Button></form></Modal> }
